version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
      
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}

      - run:
          name: install-dependencies
          command: npm i

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
